### ISSUE TITLE
Deprecate in favor of for-each?

### ISSUE THREAD

**Issue by bjnsn** [staltz/callbag-observe#2]
Since [callbag-for-each](https://github.com/staltz/callbag-for-each) supports listenables as well as pullables shouldn't the README note that as the preferred option?

**Comment by staltz** [comment]
We don't need to deprecate this package, it is useful as it is right now. for-each will send a message up the chain of callbags, and in cases where we just want to observe the downwards messages, we might not want to have those upwards messages at all, so observe is still useful.
